[package]
name = "fish-shoal-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
fish-shoal-simulator.workspace = true
egui.workspace = true
eframe.workspace = true
